services:
  backend:
    build: ./backend/
    depends_on:
      cache:
        condition: service_healthy
        restart: true
        required: true
      s3:
        condition: service_healthy
        restart: true
        required: true
    ports:
      - "8081:8081"
    volumes:
      - "./data/backend:/app"
    environment:
      RUST_LOG: backend=trace,sqlx=info,tower_http::trace::make_span=debug,info
      SQL_DB: "sqlite://database.db?mode=rwc"
      REDIS_DB: "redis://cache"
      AWS_ENDPOINT_URL: "http://s3:9000"
      AWS_REGION: default
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      S3_BUCKET: main
      S3_INIT_BUCKET_IF_NOT_EXISTS: true
      S3_FORCE_PATH_STYLE: true

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./data/minio:/mnt/data"
    command: server /mnt/data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      start_period: 10s
      start_interval: 100ms

  cache:
    image: valkey/valkey
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      start_period: 10s
      start_interval: 100ms
